title: Blog Bibliotheks- und Archivinformatik
author: Charles
email: 
description: > # this means to ignore newlines until "baseurl:"
  Vorlage für ein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik HS2020 übernommen von Dozent

# social links

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-architect
