title: Blog Bibliotheks- und Archivinformatik [My BAIN BLOG]
author: Charles Winkler
email: charles.winkler@stud.fhgr.ch
description: > # this means to ignore newlines until "baseurl:"
  Ein Lerntagebuch für den  Kurs Bibliotheks- und Archivinformatik HS2020, übernommen von Dozent Lohmeier

# social links

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-architect
